version: '3.8'

services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: presence_develop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   command: npm run dev
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/events_develop
  #   depends_on:
  #     - db

volumes:
  db_data:
